# Generated by Django 4.1.7 on 2023-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('age', models.IntegerField(max_length=2)),
                ('createdTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
