# Generated by Django 4.1.7 on 2023-02-28 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(6)]),
        ),
    ]
